#!/usr/bin/env python3
"""Generate smooth humanoid OBJ meshes aligned to humanoid_twister.xml bodies.

Run from repo:
    python3 my-env/tools/generate_human_meshes.py

No Blender required. For higher-quality sculpts, run build_realistic_character_blender.py
inside Blender after installing it.
"""

from __future__ import annotations

import math
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parents[1] / "sim" / "mjcf" / "assets" / "humanoid_meshes"


def _write_obj(path: Path, vertices: list[tuple[float, float, float]], faces: list[tuple[int, ...]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write(f"# generated by {Path(__file__).name}\n")
        for x, y, z in vertices:
            f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for face in faces:
            f.write("f " + " ".join(str(i) for i in face) + "\n")


def _add_vertex(
    vertices: list[tuple[float, float, float]],
    index_map: dict[tuple[float, float, float], int],
    x: float,
    y: float,
    z: float,
) -> int:
    key = (round(x, 6), round(y, 6), round(z, 6))
    if key not in index_map:
        index_map[key] = len(vertices) + 1
        vertices.append(key)
    return index_map[key]


def capsule(
    p0: tuple[float, float, float],
    p1: tuple[float, float, float],
    radius: float,
    *,
    segments: int = 20,
    rings: int = 10,
) -> tuple[list[tuple[float, float, float]], list[tuple[int, ...]]]:
    ax = [p1[i] - p0[i] for i in range(3)]
    length = math.sqrt(sum(a * a for a in ax))
    if length < 1e-8:
        ax = [0.0, 0.0, 1.0]
        length = 1.0
    ax = [a / length for a in ax]
    ref = (0.0, 1.0, 0.0) if abs(ax[1]) < 0.9 else (1.0, 0.0, 0.0)
    u = (
        ax[1] * ref[2] - ax[2] * ref[1],
        ax[2] * ref[0] - ax[0] * ref[2],
        ax[0] * ref[1] - ax[1] * ref[0],
    )
    u_len = math.sqrt(sum(v * v for v in u))
    u = (u[0] / u_len, u[1] / u_len, u[2] / u_len)
    v = (
        ax[1] * u[2] - ax[2] * u[1],
        ax[2] * u[0] - ax[0] * u[2],
        ax[0] * u[1] - ax[1] * u[0],
    )

    vertices: list[tuple[float, float, float]] = []
    index_map: dict[tuple[float, float, float], int] = {}
    grid: list[list[int]] = []

    def point(center: tuple[float, float, float], theta: float, phi: float, r: float) -> tuple[float, float, float]:
        ct, st = math.cos(theta), math.sin(theta)
        cp, sp = math.cos(phi), math.sin(phi)
        ox = u[0] * ct + v[0] * st
        oy = u[1] * ct + v[1] * st
        oz = u[2] * ct + v[2] * st
        return (
            center[0] + r * (ox * cp + ax[0] * sp),
            center[1] + r * (oy * cp + ax[1] * sp),
            center[2] + r * (oz * cp + ax[2] * sp),
        )

    for ri in range(rings + 1):
        row: list[int] = []
        t = ri / rings
        center = (
            p0[0] + ax[0] * length * t,
            p0[1] + ax[1] * length * t,
            p0[2] + ax[2] * length * t,
        )
        for si in range(segments):
            theta = 2.0 * math.pi * si / segments
            idx = _add_vertex(vertices, index_map, *point(center, theta, 0.0, radius))
            row.append(idx)
        grid.append(row)

    # Hemispherical caps
    cap_rows = max(4, rings // 2)
    top_center = (p1[0], p1[1], p1[2])
    bot_center = (p0[0], p0[1], p0[2])
    top_grid: list[list[int]] = []
    bot_grid: list[list[int]] = []

    for ci in range(1, cap_rows + 1):
        phi = (math.pi / 2.0) * ci / cap_rows
        row = []
        for si in range(segments):
            theta = 2.0 * math.pi * si / segments
            row.append(_add_vertex(vertices, index_map, *point(top_center, theta, phi, radius)))
        top_grid.append(row)
    for ci in range(1, cap_rows + 1):
        phi = (math.pi / 2.0) * ci / cap_rows
        row = []
        for si in range(segments):
            theta = 2.0 * math.pi * si / segments
            row.append(_add_vertex(vertices, index_map, *point(bot_center, theta, -phi, radius)))
        bot_grid.append(row)

    faces: list[tuple[int, ...]] = []

    def quad(a: int, b: int, c: int, d: int) -> None:
        faces.append((a, b, c))
        faces.append((a, c, d))

    for ri in range(len(bot_grid) - 1):
        for si in range(segments):
            s1 = (si + 1) % segments
            quad(bot_grid[ri][si], bot_grid[ri][s1], bot_grid[ri + 1][s1], bot_grid[ri + 1][si])
    for si in range(segments):
        s1 = (si + 1) % segments
        quad(bot_grid[-1][si], bot_grid[-1][s1], grid[0][s1], grid[0][si])
    for ri in range(len(grid) - 1):
        for si in range(segments):
            s1 = (si + 1) % segments
            quad(grid[ri][si], grid[ri][s1], grid[ri + 1][s1], grid[ri + 1][si])
    for si in range(segments):
        s1 = (si + 1) % segments
        quad(grid[-1][si], grid[-1][s1], top_grid[0][s1], top_grid[0][si])
    for ri in range(len(top_grid) - 1):
        for si in range(segments):
            s1 = (si + 1) % segments
            quad(top_grid[ri][si], top_grid[ri][s1], top_grid[ri + 1][s1], top_grid[ri + 1][si])

    return vertices, faces


def box(
    center: tuple[float, float, float],
    size: tuple[float, float, float],
) -> tuple[list[tuple[float, float, float]], list[tuple[int, ...]]]:
    cx, cy, cz = center
    sx, sy, sz = size
    corners = [
        (cx - sx, cy - sy, cz - sz),
        (cx + sx, cy - sy, cz - sz),
        (cx + sx, cy + sy, cz - sz),
        (cx - sx, cy + sy, cz - sz),
        (cx - sx, cy - sy, cz + sz),
        (cx + sx, cy - sy, cz + sz),
        (cx + sx, cy + sy, cz + sz),
        (cx - sx, cy + sy, cz + sz),
    ]
    faces = [
        (1, 2, 3, 4),
        (5, 6, 7, 8),
        (1, 2, 6, 5),
        (2, 3, 7, 6),
        (3, 4, 8, 7),
        (4, 1, 5, 8),
    ]
    vertices = list(corners)
    tri_faces: list[tuple[int, ...]] = []
    for a, b, c, d in faces:
        tri_faces.append((a, b, c))
        tri_faces.append((a, c, d))
    return vertices, tri_faces


def sphere(
    center: tuple[float, float, float],
    radius: float,
    *,
    segments: int = 24,
    rings: int = 16,
) -> tuple[list[tuple[float, float, float]], list[tuple[int, ...]]]:
    cx, cy, cz = center
    vertices: list[tuple[float, float, float]] = []
    index_map: dict[tuple[float, float, float], int] = {}
    grid: list[list[int]] = []
    for ri in range(rings + 1):
        phi = math.pi * ri / rings
        row: list[int] = []
        for si in range(segments):
            theta = 2.0 * math.pi * si / segments
            x = cx + radius * math.sin(phi) * math.cos(theta)
            y = cy + radius * math.sin(phi) * math.sin(theta)
            z = cz + radius * math.cos(phi)
            row.append(_add_vertex(vertices, index_map, x, y, z))
        grid.append(row)
    faces: list[tuple[int, ...]] = []
    for ri in range(rings):
        for si in range(segments):
            s1 = (si + 1) % segments
            a, b, c, d = grid[ri][si], grid[ri][s1], grid[ri + 1][s1], grid[ri + 1][si]
            faces.append((a, b, c))
            faces.append((a, c, d))
    return vertices, faces


def main() -> None:
    parts: dict[str, tuple[list[tuple[float, float, float]], list[tuple[int, ...]]]] = {
        "pelvis": capsule((0, 0, -0.02), (0, 0, 0.06), 0.085, segments=22, rings=8),
        "pelvis_shorts": box((0, 0, 0.0), (0.11, 0.09, 0.06)),
        "lumbar": capsule((0, 0, 0.0), (0, 0, 0.14), 0.10, segments=22, rings=8),
        "torso": capsule((0, 0, 0.01), (0, 0, 0.17), 0.105, segments=24, rings=10),
        "shirt": capsule((0, 0, 0.02), (0, 0, 0.165), 0.118, segments=24, rings=10),
        "head": sphere((0, 0, 0.0), 0.102, segments=28, rings=18),
        "hair": sphere((0, -0.005, 0.055), 0.108, segments=24, rings=14),
        "left_upper_arm": capsule((0, 0, 0), (0.26, 0, 0), 0.048, segments=18, rings=8),
        "left_forearm": capsule((0, 0, 0), (0.24, 0, 0), 0.042, segments=18, rings=8),
        "right_upper_arm": capsule((0, 0, 0), (-0.26, 0, 0), 0.048, segments=18, rings=8),
        "right_forearm": capsule((0, 0, 0), (-0.24, 0, 0), 0.042, segments=18, rings=8),
        "left_thigh": capsule((0, 0, 0), (0, 0, -0.34), 0.058, segments=20, rings=9),
        "left_shin": capsule((0, 0, 0), (0, 0, -0.32), 0.052, segments=20, rings=9),
        "right_thigh": capsule((0, 0, 0), (0, 0, -0.34), 0.058, segments=20, rings=9),
        "right_shin": capsule((0, 0, 0), (0, 0, -0.32), 0.052, segments=20, rings=9),
        "left_pants_thigh": capsule((0, 0, -0.02), (0, 0, -0.31), 0.065, segments=18, rings=8),
        "left_pants_shin": capsule((0, 0, -0.01), (0, 0, -0.30), 0.058, segments=18, rings=8),
        "right_pants_thigh": capsule((0, 0, -0.02), (0, 0, -0.31), 0.065, segments=18, rings=8),
        "right_pants_shin": capsule((0, 0, -0.01), (0, 0, -0.30), 0.058, segments=18, rings=8),
        "left_shoe": box((0.03, 0, -0.025), (0.11, 0.12, 0.025)),
        "right_shoe": box((-0.03, 0, -0.025), (0.11, 0.12, 0.025)),
    }

    print(f"Writing {len(parts)} meshes to {OUT_DIR}")
    for name, (verts, faces) in parts.items():
        path = OUT_DIR / f"{name}.obj"
        _write_obj(path, verts, faces)
        print(f"  {path.name}: {len(verts)} verts, {len(faces)} faces")

    print("Done.")


if __name__ == "__main__":
    main()
